apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-server-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: api-server-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-server-role-binding
subjects:
  - kind: ServiceAccount
    name: api-server-service-account
roleRef:
  kind: Role
  name: api-server-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: aroxby/refactored-waffle-api-server:main
          imagePullPolicy: Always
          env:
            - name: JOB_IMAGE_URI
              value: aroxby/refactored-waffle-background-job:main
            - name: REDIS_HOST
              value: redis
          ports:
            - containerPort: 8888
      serviceAccountName: api-server-service-account
---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: api-server
spec:
  selector:
    app: api-server
  ports:
    - port: 8888
      targetPort: 8888
  type: LoadBalancer
